services:
  tasks_backend:
    build: ./tasks_backend
    container_name: django_api
    ports:
      - "8000:8000"
    volumes:
      - ./tasks_backend:/app

  tasks_frontend:
    build: ./tasks_frontend
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./tasks_frontend:/app
      - /app/node_modules/ 
    stdin_open: true
    tty: true
    depends_on:
      - tasks_backend