version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend