# Generated by Django 5.1.6 on 2025-02-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familia'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarea'},
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='task',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_app.family', verbose_name='familia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('todo', 'Pendiente'), ('doing', 'En progreso'), ('done', 'Completada')], default='todo', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
    ]
